// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.fernflowers.com.Data;

#nullable disable

namespace api.fernflowers.com.Migrations
{
    [DbContext(typeof(VaccineDBContext))]
    [Migration("20230605185544_isapprovedtoIsApproved")]
    partial class isapprovedtoIsApproved
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.AdminSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DoseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AdminSchedules");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VaccineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VaccineId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BCG",
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "OPV",
                            VaccineId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Local",
                            VaccineId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "AMVAX B",
                            VaccineId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "ENGERIX B",
                            VaccineId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "ENGERIX B",
                            VaccineId = 4
                        },
                        new
                        {
                            Id = 7,
                            Name = "INDIRAB",
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 8,
                            Name = "VERORAB",
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 9,
                            Name = "VERORAB",
                            VaccineId = 6
                        },
                        new
                        {
                            Id = 10,
                            Name = "IMATET",
                            VaccineId = 7
                        },
                        new
                        {
                            Id = 11,
                            Name = "TT",
                            VaccineId = 7
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tetanus",
                            VaccineId = 7
                        },
                        new
                        {
                            Id = 13,
                            Name = "ROTARIX",
                            VaccineId = 8
                        },
                        new
                        {
                            Id = 14,
                            Name = "Rota Teq",
                            VaccineId = 8
                        },
                        new
                        {
                            Id = 15,
                            Name = "ROTARIX*",
                            VaccineId = 8
                        },
                        new
                        {
                            Id = 16,
                            Name = "INFANRIX HEXA",
                            VaccineId = 9
                        },
                        new
                        {
                            Id = 17,
                            Name = "HEXAXIM",
                            VaccineId = 9
                        },
                        new
                        {
                            Id = 18,
                            Name = "QUINAVAXEM + OPV",
                            VaccineId = 9
                        },
                        new
                        {
                            Id = 19,
                            Name = "EUPENTA + OPV",
                            VaccineId = 9
                        },
                        new
                        {
                            Id = 20,
                            Name = "PENTA+OPV",
                            VaccineId = 9
                        },
                        new
                        {
                            Id = 21,
                            Name = "PREVENAR*",
                            VaccineId = 10
                        },
                        new
                        {
                            Id = 22,
                            Name = "SYNFLORIX",
                            VaccineId = 10
                        },
                        new
                        {
                            Id = 23,
                            Name = "PREVENAR",
                            VaccineId = 10
                        },
                        new
                        {
                            Id = 24,
                            Name = "PENTA ( amson)",
                            VaccineId = 11
                        },
                        new
                        {
                            Id = 25,
                            Name = "Men B",
                            VaccineId = 12
                        },
                        new
                        {
                            Id = 26,
                            Name = "INFLUVAC",
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 27,
                            Name = "FLUARIX",
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 28,
                            Name = "VAXIGRIP",
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 29,
                            Name = "ANFLU",
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 30,
                            Name = "FLU",
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 31,
                            Name = "MEASLES",
                            VaccineId = 14
                        },
                        new
                        {
                            Id = 32,
                            Name = "MENACTRA",
                            VaccineId = 15
                        },
                        new
                        {
                            Id = 33,
                            Name = "NIMENRIX",
                            VaccineId = 15
                        },
                        new
                        {
                            Id = 34,
                            Name = "STAMARIL",
                            VaccineId = 16
                        },
                        new
                        {
                            Id = 35,
                            Name = "TYPHIRIX",
                            VaccineId = 17
                        },
                        new
                        {
                            Id = 36,
                            Name = "TYPBAR",
                            VaccineId = 17
                        },
                        new
                        {
                            Id = 37,
                            Name = "TYPBAR TCV",
                            VaccineId = 17
                        },
                        new
                        {
                            Id = 38,
                            Name = "TYPBAR*",
                            VaccineId = 17
                        },
                        new
                        {
                            Id = 39,
                            Name = "TYPHOID",
                            VaccineId = 17
                        },
                        new
                        {
                            Id = 40,
                            Name = "MR",
                            VaccineId = 18
                        },
                        new
                        {
                            Id = 41,
                            Name = "VARIVAC",
                            VaccineId = 19
                        },
                        new
                        {
                            Id = 42,
                            Name = "VARILRIX",
                            VaccineId = 19
                        },
                        new
                        {
                            Id = 43,
                            Name = "VAXAPOX",
                            VaccineId = 19
                        },
                        new
                        {
                            Id = 44,
                            Name = "PRIORIX TETRA",
                            VaccineId = 19
                        },
                        new
                        {
                            Id = 45,
                            Name = "VARICELLA",
                            VaccineId = 19
                        },
                        new
                        {
                            Id = 46,
                            Name = "TRIMOVAX",
                            VaccineId = 20
                        },
                        new
                        {
                            Id = 47,
                            Name = "PRIORIX",
                            VaccineId = 20
                        },
                        new
                        {
                            Id = 48,
                            Name = "MMR",
                            VaccineId = 20
                        },
                        new
                        {
                            Id = 49,
                            Name = "PRIORIX TETRA",
                            VaccineId = 20
                        },
                        new
                        {
                            Id = 50,
                            Name = "TRESIVAC",
                            VaccineId = 20
                        },
                        new
                        {
                            Id = 51,
                            Name = "HAVRIX",
                            VaccineId = 21
                        },
                        new
                        {
                            Id = 52,
                            Name = "TWINRIX",
                            VaccineId = 21
                        },
                        new
                        {
                            Id = 53,
                            Name = "AVAXIM",
                            VaccineId = 21
                        },
                        new
                        {
                            Id = 54,
                            Name = "PCV",
                            VaccineId = 22
                        },
                        new
                        {
                            Id = 55,
                            Name = "PNEUMOVAX",
                            VaccineId = 22
                        },
                        new
                        {
                            Id = 56,
                            Name = "PREVENAR",
                            VaccineId = 22
                        },
                        new
                        {
                            Id = 57,
                            Name = "BOOSTRIX",
                            VaccineId = 23
                        },
                        new
                        {
                            Id = 58,
                            Name = "BOOSTRIX",
                            VaccineId = 23
                        },
                        new
                        {
                            Id = 59,
                            Name = "Local",
                            VaccineId = 24
                        },
                        new
                        {
                            Id = 60,
                            Name = "Pfizer",
                            VaccineId = 24
                        },
                        new
                        {
                            Id = 61,
                            Name = "SinoVac",
                            VaccineId = 24
                        },
                        new
                        {
                            Id = 62,
                            Name = "Local",
                            VaccineId = 25
                        },
                        new
                        {
                            Id = 63,
                            Name = "CERVARIX",
                            VaccineId = 25
                        },
                        new
                        {
                            Id = 64,
                            Name = "Dengvaxia",
                            VaccineId = 26
                        });
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.BrandAmount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BrandAmounts");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.BrandInventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BrandInventories");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CNIC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Guardian")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsEPIDone")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsInactive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreferredSchedule")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Childs");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "b17",
                            DoctorId = 1,
                            Name = "Ali s clinic ",
                            Number = "3333333"
                        });
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.ClinicTiming", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("ClinicTimings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            Day = "Monday",
                            EndTime = new TimeSpan(0, 3, 0, 0, 0),
                            Session = "one",
                            StartTime = new TimeSpan(0, 2, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DoctorType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PMDC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ValidUpto")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorType = "Child Specialist",
                            Email = "ali.iiui1234@gmail.com",
                            IsApproved = true,
                            IsEnabled = true,
                            MobileNumber = "03352920239",
                            Name = "Ali",
                            PMDC = "a1234",
                            Password = "123",
                            ValidUpto = new DateTime(2023, 9, 5, 23, 55, 43, 934, DateTimeKind.Utc).AddTicks(7822)
                        });
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.DoctorsSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("DoseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DoctorSchedules");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Dose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<int>("MinGap")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VaccineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VaccineId");

                    b.ToTable("Doses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MinAge = 0,
                            MinGap = 0,
                            Name = "BCG",
                            VaccineId = 1
                        },
                        new
                        {
                            Id = 2,
                            MinAge = 0,
                            MinGap = 0,
                            Name = "OPV # 1",
                            VaccineId = 2
                        },
                        new
                        {
                            Id = 3,
                            MinAge = 0,
                            MinGap = 0,
                            Name = "HBV",
                            VaccineId = 3
                        },
                        new
                        {
                            Id = 4,
                            MinAge = 0,
                            MinGap = 0,
                            Name = "Hep B 1",
                            VaccineId = 4
                        },
                        new
                        {
                            Id = 5,
                            MinAge = 28,
                            MinGap = 28,
                            Name = "Hep B 2",
                            VaccineId = 4
                        },
                        new
                        {
                            Id = 6,
                            MinAge = 168,
                            MinGap = 140,
                            Name = "Hep B 3",
                            VaccineId = 4
                        },
                        new
                        {
                            Id = 7,
                            MinAge = 0,
                            MinGap = 0,
                            Name = "Pre-Exp Rabies-1",
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 8,
                            MinAge = 1,
                            MinGap = 1,
                            Name = "Pre-Exp Rabies-2",
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 9,
                            MinAge = 28,
                            MinGap = 21,
                            Name = "Pre-Exp Rabies-3",
                            VaccineId = 5
                        },
                        new
                        {
                            Id = 10,
                            MinAge = 0,
                            MinGap = 0,
                            Name = "RABIES#1",
                            VaccineId = 6
                        },
                        new
                        {
                            Id = 11,
                            MinAge = 4,
                            MinGap = 3,
                            Name = "RABIES#2",
                            VaccineId = 6
                        },
                        new
                        {
                            Id = 12,
                            MinAge = 8,
                            MinGap = 4,
                            Name = "RABIES#3",
                            VaccineId = 6
                        },
                        new
                        {
                            Id = 13,
                            MinAge = 28,
                            MinGap = 21,
                            Name = "RABIES#4",
                            VaccineId = 6
                        },
                        new
                        {
                            Id = 14,
                            MinAge = 0,
                            MinGap = 0,
                            Name = "Tetanus",
                            VaccineId = 7
                        },
                        new
                        {
                            Id = 15,
                            MinAge = 42,
                            MinGap = 0,
                            Name = "Rota Virus GE # 1",
                            VaccineId = 8
                        },
                        new
                        {
                            Id = 16,
                            MinAge = 70,
                            MinGap = 28,
                            Name = "Rota Virus GE # 2",
                            VaccineId = 8
                        },
                        new
                        {
                            Id = 17,
                            MinAge = 98,
                            MinGap = 28,
                            Name = "Rota Virus GE # 3",
                            VaccineId = 8
                        },
                        new
                        {
                            Id = 18,
                            MinAge = 42,
                            MinGap = 0,
                            Name = "OPV/IPV+HBV+DPT+Hib # 1",
                            VaccineId = 9
                        },
                        new
                        {
                            Id = 19,
                            MinAge = 70,
                            MinGap = 28,
                            Name = "OPV/IPV+HBV+DPT+Hib # 2",
                            VaccineId = 9
                        },
                        new
                        {
                            Id = 20,
                            MinAge = 98,
                            MinGap = 28,
                            Name = "OPV/IPV+HBV+DPT+Hib # 3",
                            VaccineId = 9
                        },
                        new
                        {
                            Id = 21,
                            MinAge = 365,
                            MinGap = 168,
                            Name = "OPV/IPV+HBV+DPT+Hib # 4",
                            VaccineId = 9
                        },
                        new
                        {
                            Id = 22,
                            MinAge = 42,
                            MinGap = 0,
                            Name = "Pneumococcal # 1",
                            VaccineId = 10
                        },
                        new
                        {
                            Id = 23,
                            MinAge = 70,
                            MinGap = 28,
                            Name = "Pneumococcal # 2",
                            VaccineId = 10
                        },
                        new
                        {
                            Id = 24,
                            MinAge = 98,
                            MinGap = 28,
                            Name = "Pneumococcal # 3",
                            VaccineId = 10
                        },
                        new
                        {
                            Id = 25,
                            MinAge = 365,
                            MinGap = 168,
                            Name = "Pneumococcal # 4",
                            VaccineId = 10
                        },
                        new
                        {
                            Id = 26,
                            MinAge = 42,
                            MinGap = 0,
                            Name = "HBV+DPT+Hib # 1",
                            VaccineId = 11
                        },
                        new
                        {
                            Id = 27,
                            MinAge = 70,
                            MinGap = 28,
                            Name = "HBV+DPT+Hib # 2",
                            VaccineId = 11
                        },
                        new
                        {
                            Id = 28,
                            MinAge = 98,
                            MinGap = 28,
                            Name = "HBV+DPT+Hib # 3",
                            VaccineId = 11
                        },
                        new
                        {
                            Id = 29,
                            MinAge = 56,
                            MinGap = 0,
                            Name = "MenB Vaccine # 1",
                            VaccineId = 12
                        },
                        new
                        {
                            Id = 30,
                            MinAge = 112,
                            MinGap = 56,
                            Name = "MenB Vaccine # 2",
                            VaccineId = 12
                        },
                        new
                        {
                            Id = 31,
                            MinAge = 168,
                            MinGap = 0,
                            Name = "Flu",
                            VaccineId = 13
                        },
                        new
                        {
                            Id = 32,
                            MinAge = 168,
                            MinGap = 0,
                            Name = "MEASLES # 1",
                            VaccineId = 14
                        },
                        new
                        {
                            Id = 33,
                            MinAge = 365,
                            MinGap = 168,
                            Name = "MEASLES # 2",
                            VaccineId = 14
                        },
                        new
                        {
                            Id = 34,
                            MinAge = 274,
                            MinGap = 0,
                            Name = "MenACWY # 1",
                            VaccineId = 15
                        },
                        new
                        {
                            Id = 35,
                            MinAge = 365,
                            MinGap = 84,
                            Name = "MenACWY # 2",
                            VaccineId = 15
                        },
                        new
                        {
                            Id = 36,
                            MinAge = 274,
                            MinGap = 0,
                            Name = "Yellow Fever # 1",
                            VaccineId = 16
                        },
                        new
                        {
                            Id = 37,
                            MinAge = 274,
                            MinGap = 0,
                            Name = "Typhoid",
                            VaccineId = 17
                        },
                        new
                        {
                            Id = 38,
                            MinAge = 274,
                            MinGap = 0,
                            Name = "MR#1",
                            VaccineId = 18
                        },
                        new
                        {
                            Id = 39,
                            MinAge = 365,
                            MinGap = 84,
                            Name = "MR#2",
                            VaccineId = 18
                        },
                        new
                        {
                            Id = 40,
                            MinAge = 365,
                            MinGap = 0,
                            Name = "Chicken Pox # 1",
                            VaccineId = 19
                        },
                        new
                        {
                            Id = 41,
                            MinAge = 456,
                            MinGap = 84,
                            Name = "Chicken Pox # 2",
                            VaccineId = 19
                        },
                        new
                        {
                            Id = 42,
                            MinAge = 547,
                            MinGap = 0,
                            Name = "Chicken Pox # 3",
                            VaccineId = 19
                        },
                        new
                        {
                            Id = 43,
                            MinAge = 365,
                            MinGap = 0,
                            Name = "MMR # 1",
                            VaccineId = 20
                        },
                        new
                        {
                            Id = 44,
                            MinAge = 547,
                            MinGap = 168,
                            Name = "MMR # 2",
                            VaccineId = 20
                        },
                        new
                        {
                            Id = 45,
                            MinAge = 4745,
                            MinGap = 0,
                            Name = "MMR # 3",
                            VaccineId = 20
                        },
                        new
                        {
                            Id = 46,
                            MinAge = 730,
                            MinGap = 0,
                            Name = "MMR # 4",
                            VaccineId = 20
                        },
                        new
                        {
                            Id = 47,
                            MinAge = 365,
                            MinGap = 0,
                            Name = "Hepatitis A #1",
                            VaccineId = 21
                        },
                        new
                        {
                            Id = 48,
                            MinAge = 547,
                            MinGap = 168,
                            Name = "Hepatitis A #2",
                            VaccineId = 21
                        },
                        new
                        {
                            Id = 49,
                            MinAge = 730,
                            MinGap = 0,
                            Name = "PPSV/PCV",
                            VaccineId = 22
                        },
                        new
                        {
                            Id = 50,
                            MinAge = 1825,
                            MinGap = 0,
                            Name = "DTaP # 1",
                            VaccineId = 23
                        },
                        new
                        {
                            Id = 51,
                            MinAge = 3650,
                            MinGap = 1825,
                            Name = "DTaP # 2",
                            VaccineId = 23
                        },
                        new
                        {
                            Id = 52,
                            MinAge = 3285,
                            MinGap = 0,
                            Name = "HPV # 1",
                            VaccineId = 25
                        },
                        new
                        {
                            Id = 53,
                            MinAge = 3315,
                            MinGap = 28,
                            Name = "HPV # 2",
                            VaccineId = 25
                        },
                        new
                        {
                            Id = 54,
                            MinAge = 3650,
                            MinGap = 0,
                            Name = "Dengue Fever #1",
                            VaccineId = 26
                        },
                        new
                        {
                            Id = 55,
                            MinAge = 3833,
                            MinGap = 168,
                            Name = "Dengue Fever #2",
                            VaccineId = 26
                        });
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.DoseSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("DoseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DoseSchedules");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Infinite")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Vaccines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "BCG"
                        },
                        new
                        {
                            Id = 2,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "OPV"
                        },
                        new
                        {
                            Id = 3,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "HBV"
                        },
                        new
                        {
                            Id = 4,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Hepatitis B"
                        },
                        new
                        {
                            Id = 5,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Pre-Exp RABIES"
                        },
                        new
                        {
                            Id = 6,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "PO-Ex Rabies"
                        },
                        new
                        {
                            Id = 7,
                            Infinite = true,
                            IsSpecial = false,
                            Name = "Tetanus"
                        },
                        new
                        {
                            Id = 8,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Rota Virus GE"
                        },
                        new
                        {
                            Id = 9,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "OPV/IPV+HBV+DPT+Hib"
                        },
                        new
                        {
                            Id = 10,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Pneumococcal"
                        },
                        new
                        {
                            Id = 11,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "HBV+DPT+Hib"
                        },
                        new
                        {
                            Id = 12,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "MenB vaccines"
                        },
                        new
                        {
                            Id = 13,
                            Infinite = true,
                            IsSpecial = false,
                            Name = "Flu"
                        },
                        new
                        {
                            Id = 14,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "MEASLES"
                        },
                        new
                        {
                            Id = 15,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "MenACWY"
                        },
                        new
                        {
                            Id = 16,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Yellow Fever"
                        },
                        new
                        {
                            Id = 17,
                            Infinite = true,
                            IsSpecial = false,
                            Name = "Typhoid"
                        },
                        new
                        {
                            Id = 18,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "MR"
                        },
                        new
                        {
                            Id = 19,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Chicken Pox"
                        },
                        new
                        {
                            Id = 20,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "MMR"
                        },
                        new
                        {
                            Id = 21,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Hepatitis A"
                        },
                        new
                        {
                            Id = 22,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "PPSV/PCV"
                        },
                        new
                        {
                            Id = 23,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "DTaP"
                        },
                        new
                        {
                            Id = 24,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "COVID 19"
                        },
                        new
                        {
                            Id = 25,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "HPV"
                        },
                        new
                        {
                            Id = 26,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Dengue Fever"
                        });
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Brand", b =>
                {
                    b.HasOne("api.fernflowers.com.Data.Entities.Vaccine", null)
                        .WithMany("Brands")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Dose", b =>
                {
                    b.HasOne("api.fernflowers.com.Data.Entities.Vaccine", null)
                        .WithMany("Doses")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Vaccine", b =>
                {
                    b.Navigation("Brands");

                    b.Navigation("Doses");
                });
#pragma warning restore 612, 618
        }
    }
}
