// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.fernflowers.com.Data;

#nullable disable

namespace api.fernflowers.com.Migrations
{
    [DbContext(typeof(VaccineDBContext))]
    partial class VaccineDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.AdminSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("DoseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DoseId");

                    b.ToTable("AdminSchedules");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("VaccineId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VaccineId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "BCG",
                            VaccineId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "OPV",
                            VaccineId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Local",
                            VaccineId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "AMVAX B",
                            VaccineId = 3L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "ENGERIX B",
                            VaccineId = 3L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "ENGERIX B",
                            VaccineId = 4L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "INDIRAB",
                            VaccineId = 5L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "VERORAB",
                            VaccineId = 5L
                        },
                        new
                        {
                            Id = 9L,
                            Name = "VERORAB",
                            VaccineId = 6L
                        },
                        new
                        {
                            Id = 10L,
                            Name = "IMATET",
                            VaccineId = 7L
                        },
                        new
                        {
                            Id = 11L,
                            Name = "TT",
                            VaccineId = 7L
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Tetanus",
                            VaccineId = 7L
                        },
                        new
                        {
                            Id = 13L,
                            Name = "ROTARIX",
                            VaccineId = 8L
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Rota Teq",
                            VaccineId = 8L
                        },
                        new
                        {
                            Id = 15L,
                            Name = "ROTARIX*",
                            VaccineId = 8L
                        },
                        new
                        {
                            Id = 16L,
                            Name = "INFANRIX HEXA",
                            VaccineId = 9L
                        },
                        new
                        {
                            Id = 17L,
                            Name = "HEXAXIM",
                            VaccineId = 9L
                        },
                        new
                        {
                            Id = 18L,
                            Name = "QUINAVAXEM + OPV",
                            VaccineId = 9L
                        },
                        new
                        {
                            Id = 19L,
                            Name = "EUPENTA + OPV",
                            VaccineId = 9L
                        },
                        new
                        {
                            Id = 20L,
                            Name = "PENTA+OPV",
                            VaccineId = 9L
                        },
                        new
                        {
                            Id = 21L,
                            Name = "PREVENAR*",
                            VaccineId = 10L
                        },
                        new
                        {
                            Id = 22L,
                            Name = "SYNFLORIX",
                            VaccineId = 10L
                        },
                        new
                        {
                            Id = 23L,
                            Name = "PREVENAR",
                            VaccineId = 10L
                        },
                        new
                        {
                            Id = 24L,
                            Name = "PENTA ( amson)",
                            VaccineId = 11L
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Men B",
                            VaccineId = 12L
                        },
                        new
                        {
                            Id = 26L,
                            Name = "INFLUVAC",
                            VaccineId = 13L
                        },
                        new
                        {
                            Id = 27L,
                            Name = "FLUARIX",
                            VaccineId = 13L
                        },
                        new
                        {
                            Id = 28L,
                            Name = "VAXIGRIP",
                            VaccineId = 13L
                        },
                        new
                        {
                            Id = 29L,
                            Name = "ANFLU",
                            VaccineId = 13L
                        },
                        new
                        {
                            Id = 30L,
                            Name = "FLU",
                            VaccineId = 13L
                        },
                        new
                        {
                            Id = 31L,
                            Name = "MEASLES",
                            VaccineId = 14L
                        },
                        new
                        {
                            Id = 32L,
                            Name = "MENACTRA",
                            VaccineId = 15L
                        },
                        new
                        {
                            Id = 33L,
                            Name = "NIMENRIX",
                            VaccineId = 15L
                        },
                        new
                        {
                            Id = 34L,
                            Name = "STAMARIL",
                            VaccineId = 16L
                        },
                        new
                        {
                            Id = 35L,
                            Name = "TYPHIRIX",
                            VaccineId = 17L
                        },
                        new
                        {
                            Id = 36L,
                            Name = "TYPBAR",
                            VaccineId = 17L
                        },
                        new
                        {
                            Id = 37L,
                            Name = "TYPBAR TCV",
                            VaccineId = 17L
                        },
                        new
                        {
                            Id = 38L,
                            Name = "TYPBAR*",
                            VaccineId = 17L
                        },
                        new
                        {
                            Id = 39L,
                            Name = "TYPHOID",
                            VaccineId = 17L
                        },
                        new
                        {
                            Id = 40L,
                            Name = "MR",
                            VaccineId = 18L
                        },
                        new
                        {
                            Id = 41L,
                            Name = "VARIVAC",
                            VaccineId = 19L
                        },
                        new
                        {
                            Id = 42L,
                            Name = "VARILRIX",
                            VaccineId = 19L
                        },
                        new
                        {
                            Id = 43L,
                            Name = "VAXAPOX",
                            VaccineId = 19L
                        },
                        new
                        {
                            Id = 44L,
                            Name = "PRIORIX TETRA",
                            VaccineId = 19L
                        },
                        new
                        {
                            Id = 45L,
                            Name = "VARICELLA",
                            VaccineId = 19L
                        },
                        new
                        {
                            Id = 46L,
                            Name = "TRIMOVAX",
                            VaccineId = 20L
                        },
                        new
                        {
                            Id = 47L,
                            Name = "PRIORIX",
                            VaccineId = 20L
                        },
                        new
                        {
                            Id = 48L,
                            Name = "MMR",
                            VaccineId = 20L
                        },
                        new
                        {
                            Id = 49L,
                            Name = "PRIORIX TETRA",
                            VaccineId = 20L
                        },
                        new
                        {
                            Id = 50L,
                            Name = "TRESIVAC",
                            VaccineId = 20L
                        },
                        new
                        {
                            Id = 51L,
                            Name = "HAVRIX",
                            VaccineId = 21L
                        },
                        new
                        {
                            Id = 52L,
                            Name = "TWINRIX",
                            VaccineId = 21L
                        },
                        new
                        {
                            Id = 53L,
                            Name = "AVAXIM",
                            VaccineId = 21L
                        },
                        new
                        {
                            Id = 54L,
                            Name = "PCV",
                            VaccineId = 22L
                        },
                        new
                        {
                            Id = 55L,
                            Name = "PNEUMOVAX",
                            VaccineId = 22L
                        },
                        new
                        {
                            Id = 56L,
                            Name = "PREVENAR",
                            VaccineId = 22L
                        },
                        new
                        {
                            Id = 57L,
                            Name = "BOOSTRIX",
                            VaccineId = 23L
                        },
                        new
                        {
                            Id = 58L,
                            Name = "BOOSTRIX",
                            VaccineId = 23L
                        },
                        new
                        {
                            Id = 59L,
                            Name = "Local",
                            VaccineId = 24L
                        },
                        new
                        {
                            Id = 60L,
                            Name = "Pfizer",
                            VaccineId = 24L
                        },
                        new
                        {
                            Id = 61L,
                            Name = "SinoVac",
                            VaccineId = 24L
                        },
                        new
                        {
                            Id = 62L,
                            Name = "Local",
                            VaccineId = 25L
                        },
                        new
                        {
                            Id = 63L,
                            Name = "CERVARIX",
                            VaccineId = 25L
                        },
                        new
                        {
                            Id = 64L,
                            Name = "Dengvaxia",
                            VaccineId = 26L
                        });
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.BrandAmount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BrandAmounts");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.BrandInventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BrandInventories");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Child", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ClinicId")
                        .HasColumnType("bigint");

                    b.Property<string>("CnicOrPassPort")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Guardian")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEPIDone")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SelectCnicOrPassport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Childs");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Clinic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Fees")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "b17",
                            City = "Isb",
                            DoctorId = 1L,
                            Fees = "100",
                            IsOnline = true,
                            Name = "Ali s clinic ",
                            Number = "3333333"
                        });
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.ClinicTiming", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ClinicId")
                        .HasColumnType("bigint");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("ClinicTimings");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClinicId = 1L,
                            Day = "Monday",
                            EndTime = new TimeSpan(0, 3, 0, 0, 0),
                            Session = "Morning",
                            StartTime = new TimeSpan(0, 2, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PMDC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("ValidUpto")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "ali.iiui1234@gmail.com",
                            MobileNumber = "03352920239",
                            Name = "Ali",
                            PMDC = "a1234",
                            Password = "123",
                            ValidUpto = new DateOnly(2023, 7, 26)
                        });
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.DoctorSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<long>("DoseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DoseId");

                    b.ToTable("DoctorSchedules");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Dose", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<string>("MinAgeText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("VaccineId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VaccineId");

                    b.ToTable("Doses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MinAge = 0,
                            MinAgeText = "At Birth",
                            Name = "BCG",
                            VaccineId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            MinAge = 0,
                            MinAgeText = "At Birth",
                            Name = "OPV # 1",
                            VaccineId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            MinAge = 0,
                            MinAgeText = "At Birth",
                            Name = "HBV",
                            VaccineId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            MinAge = 0,
                            MinAgeText = "At Birth",
                            Name = "Hep B 1",
                            VaccineId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            MinAge = 29,
                            MinAgeText = "4 Weeks",
                            Name = "Hep B 2",
                            VaccineId = 4L
                        },
                        new
                        {
                            Id = 6L,
                            MinAge = 169,
                            MinAgeText = "6 Months",
                            Name = "Hep B 3",
                            VaccineId = 4L
                        },
                        new
                        {
                            Id = 7L,
                            MinAge = 0,
                            MinAgeText = "At Birth",
                            Name = "Pre-Exp Rabies-1",
                            VaccineId = 5L
                        },
                        new
                        {
                            Id = 8L,
                            MinAge = 1,
                            MinAgeText = "1 Day",
                            Name = "Pre-Exp Rabies-2",
                            VaccineId = 5L
                        },
                        new
                        {
                            Id = 9L,
                            MinAge = 29,
                            MinAgeText = "4 Weeks",
                            Name = "Pre-Exp Rabies-3",
                            VaccineId = 5L
                        },
                        new
                        {
                            Id = 10L,
                            MinAge = 0,
                            MinAgeText = "At Birth",
                            Name = "RABIES#1",
                            VaccineId = 6L
                        },
                        new
                        {
                            Id = 11L,
                            MinAge = 4,
                            MinAgeText = "4 Days",
                            Name = "RABIES#2",
                            VaccineId = 6L
                        },
                        new
                        {
                            Id = 12L,
                            MinAge = 8,
                            MinAgeText = "8 Days",
                            Name = "RABIES#3",
                            VaccineId = 6L
                        },
                        new
                        {
                            Id = 13L,
                            MinAge = 29,
                            MinAgeText = "4 Weeks",
                            Name = "RABIES#4",
                            VaccineId = 6L
                        },
                        new
                        {
                            Id = 14L,
                            MinAge = 0,
                            MinAgeText = "At Birth",
                            Name = "Tetanus",
                            VaccineId = 7L
                        },
                        new
                        {
                            Id = 15L,
                            MinAge = 43,
                            MinAgeText = "6 Weeks",
                            Name = "Rota Virus GE # 1",
                            VaccineId = 8L
                        },
                        new
                        {
                            Id = 16L,
                            MinAge = 71,
                            MinAgeText = "10 Weeks",
                            Name = "Rota Virus GE # 2",
                            VaccineId = 8L
                        },
                        new
                        {
                            Id = 17L,
                            MinAge = 99,
                            MinAgeText = "14 Weeks",
                            Name = "Rota Virus GE # 3",
                            VaccineId = 8L
                        },
                        new
                        {
                            Id = 18L,
                            MinAge = 43,
                            MinAgeText = "6 Weeks",
                            Name = "OPV/IPV+HBV+DPT+Hib # 1",
                            VaccineId = 9L
                        },
                        new
                        {
                            Id = 19L,
                            MinAge = 71,
                            MinAgeText = "10 Weeks",
                            Name = "OPV/IPV+HBV+DPT+Hib # 2",
                            VaccineId = 9L
                        },
                        new
                        {
                            Id = 20L,
                            MinAge = 99,
                            MinAgeText = "14 Weeks",
                            Name = "OPV/IPV+HBV+DPT+Hib # 3",
                            VaccineId = 9L
                        },
                        new
                        {
                            Id = 21L,
                            MinAge = 365,
                            MinAgeText = "1 Year",
                            Name = "OPV/IPV+HBV+DPT+Hib # 4",
                            VaccineId = 9L
                        },
                        new
                        {
                            Id = 22L,
                            MinAge = 43,
                            MinAgeText = "6 Weeks",
                            Name = "Pneumococcal # 1",
                            VaccineId = 10L
                        },
                        new
                        {
                            Id = 23L,
                            MinAge = 71,
                            MinAgeText = "10 Weeks",
                            Name = "Pneumococcal # 2",
                            VaccineId = 10L
                        },
                        new
                        {
                            Id = 24L,
                            MinAge = 99,
                            MinAgeText = "14 Weeks",
                            Name = "Pneumococcal # 3",
                            VaccineId = 10L
                        },
                        new
                        {
                            Id = 25L,
                            MinAge = 365,
                            MinAgeText = "1 Year",
                            Name = "Pneumococcal # 4",
                            VaccineId = 10L
                        },
                        new
                        {
                            Id = 26L,
                            MinAge = 43,
                            MinAgeText = "6 Weeks",
                            Name = "HBV+DPT+Hib # 1",
                            VaccineId = 11L
                        },
                        new
                        {
                            Id = 27L,
                            MinAge = 71,
                            MinAgeText = "10 Weeks",
                            Name = "HBV+DPT+Hib # 2",
                            VaccineId = 11L
                        },
                        new
                        {
                            Id = 28L,
                            MinAge = 99,
                            MinAgeText = "14 Weeks",
                            Name = "HBV+DPT+Hib # 3",
                            VaccineId = 11L
                        },
                        new
                        {
                            Id = 29L,
                            MinAge = 57,
                            MinAgeText = "8 Weeks",
                            Name = "MenB Vaccine # 1",
                            VaccineId = 12L
                        },
                        new
                        {
                            Id = 30L,
                            MinAge = 113,
                            MinAgeText = "16 Weeks",
                            Name = "MenB Vaccine # 2",
                            VaccineId = 12L
                        },
                        new
                        {
                            Id = 31L,
                            MinAge = 169,
                            MinAgeText = "6 Months",
                            Name = "Flu",
                            VaccineId = 13L
                        },
                        new
                        {
                            Id = 32L,
                            MinAge = 169,
                            MinAgeText = "6 Months",
                            Name = "MEASLES # 1",
                            VaccineId = 14L
                        },
                        new
                        {
                            Id = 33L,
                            MinAge = 365,
                            MinAgeText = "1 Year",
                            Name = "MEASLES # 2",
                            VaccineId = 14L
                        },
                        new
                        {
                            Id = 34L,
                            MinAge = 275,
                            MinAgeText = "9 Months",
                            Name = "MenACWY # 1",
                            VaccineId = 15L
                        },
                        new
                        {
                            Id = 35L,
                            MinAge = 365,
                            MinAgeText = "1 Year",
                            Name = "MenACWY # 2",
                            VaccineId = 15L
                        },
                        new
                        {
                            Id = 36L,
                            MinAge = 275,
                            MinAgeText = "9 Months",
                            Name = "Yellow Fever # 1",
                            VaccineId = 16L
                        },
                        new
                        {
                            Id = 37L,
                            MinAge = 275,
                            MinAgeText = "9 Months",
                            Name = "Typhoid",
                            VaccineId = 17L
                        },
                        new
                        {
                            Id = 38L,
                            MinAge = 275,
                            MinAgeText = "9 Months",
                            Name = "MR#1",
                            VaccineId = 18L
                        },
                        new
                        {
                            Id = 39L,
                            MinAge = 365,
                            MinAgeText = "1 Year",
                            Name = "MR#2",
                            VaccineId = 18L
                        },
                        new
                        {
                            Id = 40L,
                            MinAge = 365,
                            MinAgeText = "1 Year",
                            Name = "Chicken Pox # 1",
                            VaccineId = 19L
                        },
                        new
                        {
                            Id = 41L,
                            MinAge = 457,
                            MinAgeText = "15 Months",
                            Name = "Chicken Pox # 2",
                            VaccineId = 19L
                        },
                        new
                        {
                            Id = 42L,
                            MinAge = 548,
                            MinAgeText = "18 Months",
                            Name = "Chicken Pox # 3",
                            VaccineId = 19L
                        },
                        new
                        {
                            Id = 43L,
                            MinAge = 365,
                            MinAgeText = "1 Year",
                            Name = "MMR # 1",
                            VaccineId = 20L
                        },
                        new
                        {
                            Id = 44L,
                            MinAge = 548,
                            MinAgeText = "18 Months",
                            Name = "MMR # 2",
                            VaccineId = 20L
                        },
                        new
                        {
                            Id = 45L,
                            MinAge = 4746,
                            MinAgeText = "13 Year",
                            Name = "MMR # 3",
                            VaccineId = 20L
                        },
                        new
                        {
                            Id = 46L,
                            MinAge = 731,
                            MinAgeText = "2 Year",
                            Name = "MMR # 4",
                            VaccineId = 20L
                        },
                        new
                        {
                            Id = 47L,
                            MinAge = 365,
                            MinAgeText = "1 Year",
                            Name = "Hepatitis A #1",
                            VaccineId = 21L
                        },
                        new
                        {
                            Id = 48L,
                            MinAge = 548,
                            MinAgeText = "18 Months",
                            Name = "Hepatitis A #2",
                            VaccineId = 21L
                        },
                        new
                        {
                            Id = 49L,
                            MinAge = 731,
                            MinAgeText = "2 Year",
                            Name = "PPSV/PCV",
                            VaccineId = 22L
                        },
                        new
                        {
                            Id = 50L,
                            MinAge = 1826,
                            MinAgeText = "5 Year",
                            Name = "DTaP # 1",
                            VaccineId = 23L
                        },
                        new
                        {
                            Id = 51L,
                            MinAge = 3651,
                            MinAgeText = "10 Year",
                            Name = "DTaP # 2",
                            VaccineId = 23L
                        },
                        new
                        {
                            Id = 52L,
                            MinAge = 3286,
                            MinAgeText = "9 Year",
                            Name = "HPV # 1",
                            VaccineId = 25L
                        },
                        new
                        {
                            Id = 53L,
                            MinAge = 3316,
                            MinAgeText = "1 Year 1 Month",
                            Name = "HPV # 2",
                            VaccineId = 25L
                        },
                        new
                        {
                            Id = 54L,
                            MinAge = 3651,
                            MinAgeText = "10 Year",
                            Name = "Dengue Fever #1",
                            VaccineId = 26L
                        },
                        new
                        {
                            Id = 55L,
                            MinAge = 3834,
                            MinAgeText = "10 Year 6 Months",
                            Name = "Dengue Fever #2",
                            VaccineId = 26L
                        });
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.PatientSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChildId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DoseId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("GivenDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDone")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSkip")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DoseId");

                    b.ToTable("PatientSchedules");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Vaccine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Infinite")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Vaccines");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "BCG"
                        },
                        new
                        {
                            Id = 2L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "OPV"
                        },
                        new
                        {
                            Id = 3L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "HBV"
                        },
                        new
                        {
                            Id = 4L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Hepatitis B"
                        },
                        new
                        {
                            Id = 5L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Pre-Exp RABIES"
                        },
                        new
                        {
                            Id = 6L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "PO-Ex Rabies"
                        },
                        new
                        {
                            Id = 7L,
                            Infinite = true,
                            IsSpecial = false,
                            Name = "Tetanus"
                        },
                        new
                        {
                            Id = 8L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Rota Virus GE"
                        },
                        new
                        {
                            Id = 9L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "OPV/IPV+HBV+DPT+Hib"
                        },
                        new
                        {
                            Id = 10L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Pneumococcal"
                        },
                        new
                        {
                            Id = 11L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "HBV+DPT+Hib"
                        },
                        new
                        {
                            Id = 12L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "MenB vaccines"
                        },
                        new
                        {
                            Id = 13L,
                            Infinite = true,
                            IsSpecial = false,
                            Name = "Flu"
                        },
                        new
                        {
                            Id = 14L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "MEASLES"
                        },
                        new
                        {
                            Id = 15L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "MenACWY"
                        },
                        new
                        {
                            Id = 16L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Yellow Fever"
                        },
                        new
                        {
                            Id = 17L,
                            Infinite = true,
                            IsSpecial = false,
                            Name = "Typhoid"
                        },
                        new
                        {
                            Id = 18L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "MR"
                        },
                        new
                        {
                            Id = 19L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Chicken Pox"
                        },
                        new
                        {
                            Id = 20L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "MMR"
                        },
                        new
                        {
                            Id = 21L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Hepatitis A"
                        },
                        new
                        {
                            Id = 22L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "PPSV/PCV"
                        },
                        new
                        {
                            Id = 23L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "DTaP"
                        },
                        new
                        {
                            Id = 24L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "COVID 19"
                        },
                        new
                        {
                            Id = 25L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "HPV"
                        },
                        new
                        {
                            Id = 26L,
                            Infinite = false,
                            IsSpecial = false,
                            Name = "Dengue Fever"
                        });
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.AdminSchedule", b =>
                {
                    b.HasOne("api.fernflowers.com.Data.Entities.Dose", "Dose")
                        .WithMany()
                        .HasForeignKey("DoseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dose");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Brand", b =>
                {
                    b.HasOne("api.fernflowers.com.Data.Entities.Vaccine", null)
                        .WithMany("Brands")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Clinic", b =>
                {
                    b.HasOne("api.fernflowers.com.Data.Entities.Doctor", null)
                        .WithMany("Clinics")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.ClinicTiming", b =>
                {
                    b.HasOne("api.fernflowers.com.Data.Entities.Clinic", null)
                        .WithMany("ClinicTimings")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.DoctorSchedule", b =>
                {
                    b.HasOne("api.fernflowers.com.Data.Entities.Dose", "Dose")
                        .WithMany()
                        .HasForeignKey("DoseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dose");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Dose", b =>
                {
                    b.HasOne("api.fernflowers.com.Data.Entities.Vaccine", null)
                        .WithMany("Doses")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.PatientSchedule", b =>
                {
                    b.HasOne("api.fernflowers.com.Data.Entities.Dose", "Dose")
                        .WithMany()
                        .HasForeignKey("DoseId");

                    b.Navigation("Dose");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Clinic", b =>
                {
                    b.Navigation("ClinicTimings");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Doctor", b =>
                {
                    b.Navigation("Clinics");
                });

            modelBuilder.Entity("api.fernflowers.com.Data.Entities.Vaccine", b =>
                {
                    b.Navigation("Brands");

                    b.Navigation("Doses");
                });
#pragma warning restore 612, 618
        }
    }
}
